manager/urls.py
from django.urls import path

from .views import (
    index,
    WorkerListView,
    TaskListView,
    TaskTypeListView,
    PositionListView,
    WorkerCreateView,
    WorkerDetailView,
    WorkerDeleteView,
    WorkerUpdateView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    TaskDetailView,
    PositionCreateView,
    PositionDetailView,
    PositionDeleteView,
    TaskTypeCreateView,
    TaskTypeDetailView,
    TaskTypeDeleteView,
    CompleteTaskView,
    RejectTaskView,
    PositionUpdateView,

)

urlpatterns = [
    path("", index, name="index"),
    path(
        "task-types/",
        TaskTypeListView.as_view(),
        name="task-type-list",
    ),
    path("tasks/", TaskListView.as_view(), name="task-list"),
    path("tasks/<int:pk>/", TaskDetailView.as_view(), name="task-detail"),
    path("tasks/create/", TaskCreateView.as_view(), name="task-create"),
    path("tasks/<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"),
    path("tasks/<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),
    path("workers/", WorkerListView.as_view(), name="worker-list"),
    path(
        "workers/<int:pk>/", WorkerDetailView.as_view(), name="worker-detail"
    ),
    path("workers/create/", WorkerCreateView.as_view(), name="worker-create"),
    path(
        "workers/<int:pk>/update/",
        WorkerUpdateView.as_view(),
        name="worker-update",
    ),
    path(
        "workers/<int:pk>/delete/",
        WorkerDeleteView.as_view(),
        name="worker-delete",
    ),
    path(
        "positions/",
        PositionListView.as_view(),
        name="position-list",
    ),
    path(
        "posiitions/create/",
        PositionCreateView.as_view(),
        name="position-create",
    ),
    path("positions/<int:pk>/", PositionDetailView.as_view(), name="position-detail"),
    path("positions/<int:pk>/update/", PositionUpdateView.as_view(), name="position-update"),
    path("positions/<int:pk>/delete/", PositionDeleteView.as_view(), name="position-delete"),
    path(
        "task-types/create/",
        TaskTypeCreateView.as_view(),
        name="task-type-create",
    ),
    path(
        "task-types/<int:pk>/",
        TaskTypeDetailView.as_view(),
        name="task-type-detail",
    ),
    path(
        "task-types/<int:pk>/delete/",
        TaskTypeDeleteView.as_view(),
        name="task-type-delete",
    ),
    path('task/<int:pk>/complete/', CompleteTaskView.as_view(), name='task-complete'),
    path('task/<int:pk>/reject/', RejectTaskView.as_view(), name='task-reject'),

]

app_name = "manager"

task_manager/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from manager import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("manager.urls", namespace="manager")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("register", views.register_request, name="register"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

manager/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

from manager.models import Worker, Task, Position


# class ListWidget(forms.Textarea):
#     def __init__(self, *args, **kwargs):
#         self.new_item_text = kwargs.pop('new_item_text', 'Add a new item')
#         super().__init__(*args, **kwargs)
#
#     def render(self, name, value, attrs=None, renderer=None):
#         if value is None:
#             value = ''
#         output = '<ul>'
#         for line in value.split('\n'):
#             output += f'<li>{line.strip()}</li>'
#         output += '</ul>'
#         output += f'<input type="text" placeholder="{self.new_item_text}">'
#         return output


class TaskForm(forms.ModelForm):
    assignees = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

    deadline = forms.DateField(
        input_formats=['%Y-%m-%dT%H:%M'],
        widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}),
        required=False
    )

    class Meta:
        model = Task
        fields = "__all__"

    def save(self, commit=True):
        task = super().save(commit=False)
        if commit:
            task.save()
            self.save_m2m()
        return task


class PositionForm(forms.ModelForm):
    class Meta:
        model = Position
        fields = "__all__"


class WorkerCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Worker
        fields = UserCreationForm.Meta.fields + (
            "position",
            "first_name",
            "last_name",
        )


class WorkerUpdateForm(forms.ModelForm):
    class Meta:
        model = Worker
        fields = ["first_name", "last_name", "position", "email"]


class WorkerSearchForm(forms.Form):
    username = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by username..."})
    )


class TaskSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by task..."})
    )


class TaskTypeSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={"placeholder": "Search by task type..."})
    )


class PositionSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={"placeholder": "Search by position..."})
    )


class NewWorkerForm(UserCreationForm):
    # email = forms.EmailField(required=True)

    class Meta:
        model = Worker
        fields = ("username", "first_name", "last_name", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(NewWorkerForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user

manager/views.py
import datetime
from datetime import date


from django.contrib import messages
from django.contrib.auth import get_user_model, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.utils import timezone
from django.views import generic
from django.views.generic import DetailView

from manager.forms import WorkerSearchForm, TaskSearchForm, TaskTypeSearchForm, WorkerCreationForm, WorkerUpdateForm, \
    TaskForm, PositionSearchForm, PositionForm, NewWorkerForm
from manager.models import Worker, Task, TaskType, Position


@login_required
def index(request):
    """View function for the home page of the site."""

    num_workers = Worker.objects.count()
    num_tasks = Task.objects.count()
    num_task_types = TaskType.objects.count()
    num_positions = Position.objects.count()

    context = {
        "num_workers": num_workers,
        "num_positions": num_positions,
        "num_tasks": num_tasks,
        "num_task_types": num_task_types,
    }

    return render(request, "manager/index.html", context=context)


# -----------------------------------------------------------------------------------------------------------
#
class TaskTypeListView(LoginRequiredMixin, generic.ListView):
    model = TaskType
    context_object_name = "task_type_list"
    template_name = "manager/task_type_list.html"
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(TaskTypeListView, self).get_context_data(**kwargs)

        name = self.request.GET.get("name", "")

        context["search_form"] = TaskTypeSearchForm(initial={
            "name": name
        })

        return context

    def get_queryset(self):
        queryset = TaskType.objects.all()
        form = TaskTypeSearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(
                name__icontains=form.cleaned_data["name"]
            )

        return queryset


#
#
class TaskTypeCreateView(LoginRequiredMixin, generic.CreateView):
    model = TaskType
    fields = "__all__"
    template_name = "manager/task_type_create.html"
    success_url = reverse_lazy("manager:task-type-create")


class TaskTypeDetailView(LoginRequiredMixin, generic.DetailView):
    model = TaskType
    template_name = "manager/task_type_detail.html"


class TaskTypeUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = TaskType
    fields = "__all__"
    success_url = reverse_lazy("manage:task-type-list")


class PositionUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Position
    fields = "__all__"
    success_url = reverse_lazy("manage:position-list")


#
#
class TaskTypeDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = TaskType
    template_name = "manager/task_type_confirm_delete.html"
    success_url = reverse_lazy("manage:task-type-list")


#
#
class TaskListView(LoginRequiredMixin, generic.ListView):
    model = Task
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(TaskListView, self).get_context_data(**kwargs)

        name = self.request.GET.get("name", "")

        expired_task = Task.objects.filter(deadline__lt=timezone.now())
        # uncompleted_tasks = Task.objects.filter( is_completed=False)

        context["expired_task"] = expired_task
        # context["uncompleted_tasks"] = uncompleted_tasks

        context["search_form"] = TaskSearchForm(initial={
            "name": name
        })

        return context

    def get_queryset(self):
        queryset = Task.objects.all().select_related("task_type")
        form = TaskSearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(
                name__icontains=form.cleaned_data["name"]
            )

        return queryset


#
#
class TaskDetailView(LoginRequiredMixin, generic.DetailView):
    model = Task


#
#
class TaskCreateView(LoginRequiredMixin, generic.CreateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("manager:task-list")


class TaskUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("manager:task-list")


class TaskDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Task
    success_url = reverse_lazy("manager:task-list")


class WorkerListView(LoginRequiredMixin, generic.ListView):
    model = Worker
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(WorkerListView, self).get_context_data(**kwargs)

        username = self.request.GET.get("username", "")

        context["search_form"] = WorkerSearchForm(initial={
            "username": username
        })

        return context

    def get_queryset(self):
        queryset = get_user_model().objects.all()
        form = WorkerSearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(
                username__icontains=form.cleaned_data["username"]
            )

        return queryset


# class WorkerDetailView(LoginRequiredMixin, generic.DetailView):
#     model = Worker
#     queryset = Worker.objects.all().prefetch_related("tasks__task_type")
#
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         worker = self.object
#
#         completed_tasks = Task.objects.filter(assignees=worker, is_completed=True)
#         uncompleted_tasks = Task.objects.filter(assignees=worker, is_completed=False)
#
#         context["completed_tasks"] = completed_tasks
#         context["uncompleted_tasks"] = uncompleted_tasks
#
#         return context


class WorkerDetailView(LoginRequiredMixin, generic.DetailView):
    model = Worker
    queryset = Worker.objects.all().prefetch_related("tasks__task_type")
    paginate_by = 2

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        worker = self.object

        completed_tasks = Task.objects.filter(assignees=worker, is_completed=True)
        uncompleted_tasks = Task.objects.filter(assignees=worker, is_completed=False)

        # Pagination for completed tasks
        completed_tasks_paginator = Paginator(completed_tasks, self.paginate_by)
        completed_tasks_page_number = self.request.GET.get('completed_tasks_page')
        completed_tasks_page = completed_tasks_paginator.get_page(completed_tasks_page_number)

        # Pagination for uncompleted tasks
        uncompleted_tasks_paginator = Paginator(uncompleted_tasks, self.paginate_by)
        uncompleted_tasks_page_number = self.request.GET.get('uncompleted_tasks_page')
        uncompleted_tasks_page = uncompleted_tasks_paginator.get_page(uncompleted_tasks_page_number)

        context["completed_tasks"] = completed_tasks_page
        context["uncompleted_tasks"] = uncompleted_tasks_page

        return context


class WorkerCreateView(LoginRequiredMixin, generic.CreateView):
    model = Worker
    form_class = WorkerCreationForm


class WorkerUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Worker
    form_class = WorkerUpdateForm
    success_url = reverse_lazy("manager:worker-list")


#
#
class WorkerDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Worker
    success_url = reverse_lazy("")


class PositionListView(LoginRequiredMixin, generic.ListView):
    model = Position
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(PositionListView, self).get_context_data(**kwargs)

        name = self.request.GET.get("name", "")

        context["search_form"] = PositionSearchForm(initial={
            "name": name
        })

        return context

    def get_queryset(self):
        queryset = Position.objects.all()
        form = PositionSearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(
                name__icontains=form.cleaned_data["name"]
            )

        return queryset


class PositionCreateView(LoginRequiredMixin, generic.CreateView):
    model = Position
    form_class = PositionForm
    success_url = reverse_lazy("manager:position-list")


class PositionDetailView(LoginRequiredMixin, generic.DetailView):
    model = Position
    queryset = Position.objects.all()


class PositionDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Position
    success_url = reverse_lazy("")


class CompleteTaskView(LoginRequiredMixin, DetailView):
    model = Task
    template_name = 'manager/task_detail.html'

    def post(self, request, *args, **kwargs):
        task = self.get_object()
        task.is_completed = True
        # task.complete_date = timezone.now() # added new string
        task.save()
        return redirect(reverse_lazy('manager:task-detail', kwargs={'pk': task.pk}))


def register_request(request):
    if request.method == "POST":
        form = NewWorkerForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, "Registration successful.")
            return redirect("manager:index")
        messages.error(request, "Unsuccessful registration. Invalid information.")
    form = NewWorkerForm()
    return render(request=request, template_name="registration/register.html", context={"register_form": form})


class RejectTaskView(LoginRequiredMixin, DetailView):

templates/manager/index.html
{% extends "base.html" %}

{% block content %}
    <div class="jumbotron text-center">
        <h1 class="display-4">Task Manager</h1>
        <p class="lead">Welcome to our task manager!</p>
    </div>
    <div class="container text-center">
        <h2>Some information about us:</h2>
        <div class="row">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">{{ num_workers }}</h5>
                        <a class="card-text" href="{% url 'manager:worker-list' %}" style="color: black;">Workers</a>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">{{ num_positions }}</h5>
                        <a class="card-text" href="{% url 'manager:position-list' %}" style="color: black;">Positions</a>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">{{ num_tasks }}</h5>
                        <a class="card-text" href="{% url 'manager:task-list' %}" style="color: black;">Tasks</a>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">{{ num_task_types }}</h5>
                        <a class="card-text" href="{% url 'manager:task-type-list' %}" style="color: black;">Task types</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}


templates/manager/position_confirm_delete.html
{% extends "base.html" %}

{% block content %}

  <div class="container my-5">
    <div class="row justify-content-center">
      <div class="col-md-6">
        <div class="card">
          <div class="card-body">
            <h1 class="card-title mb-4">Delete this position?</h1>
            <p class="card-text">Are you sure you want to delete this position?</p>
            <form action="" method="post">
              {% csrf_token %}
              <div class="d-flex justify-content-between mt-4">
                <input type="submit" value="Yes" class="btn btn-danger">
                <a href="#" class="btn btn-secondary" onclick="history.back()">Cancel</a>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/manager/position_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} position</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/manager/position_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <br>
  <div class="row justify-content-center">
    <div class="col-lg-8">
      <div class="card">
        <div class="card-body">
          <h1 class="card-title">
            Our workers positions:
            <a href="{% url 'manager:position-create' %}" class="btn btn-dark float-right">
              Create
            </a>
          </h1>

          <br>

          <form action="" method="get" class="form-inline">
            {{ search_form|crispy }}
            <input type="submit" value="Search" class="btn btn-dark">
          </form>

          <br>

          {% if position_list %}
          <div class="table-responsive">
            <table class="table table-hover">
              <thead class="thead-dark">
                <tr>
                  <th>ID</th>
                  <th>Name</th>
                  <th>Number of workers</th>
                </tr>
              </thead>
              <tbody>
              {% for position in position_list %}
                <tr>
                  <td>{{ position.id }}</td>
                  <td><a href="{% url "manager:position-detail" pk=position.id %} ">{{ position.name }}</a></td>
                  <td>{{ position.workers.count }}</td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
          </div>
          {% else %}
            <p>There are no positions in order.</p>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/manager/worker_detail.html
{#{% extends "base.html" %}#}
{##}
{#{% block content %}#}
{#  <br>#}
{#  <div class="container">#}
{#    <h1>#}
{#      Username: {{ worker.username }}#}
{#      <a href="{% url 'manager:worker-delete' pk=worker.id %}" class="btn btn-danger link-to-page">Delete</a>#}
{#      <a href="{% url 'manager:worker-update' pk=worker.id %}" class="btn btn-secondary link-to-page">Update worker info</a>#}
{#    </h1>#}
{##}
{#    <hr>#}
{##}
{#    <div class="row">#}
{#      <div class="col-md-6">#}
{#        <h3>Personal Information</h3>#}
{#        <table class="table table-striped">#}
{#          <tr>#}
{#            <td><strong>First name:</strong></td>#}
{#            <td>{{ worker.first_name }}</td>#}
{#          </tr>#}
{#          <tr>#}
{#            <td><strong>Last name:</strong></td>#}
{#            <td>{{ worker.last_name }}</td>#}
{#          </tr>#}
{#          <tr>#}
{#            <td><strong>Position:</strong></td>#}
{#            <td>{{ worker.position }}</td>#}
{#          </tr>#}
{#        </table>#}
{#      </div>#}
{##}
{#      <div class="col-md-6">#}
{#        <h3>Tasks</h3>#}
{#        <h4>Completed tasks ✔️</h4>#}
{#        {% if completed_tasks %}#}
{#          {% for task in completed_tasks %}#}
{#            <hr>#}
{#            <p><strong>Name:</strong> <a href="{{ task.get_absolute_url }}">{{ task.name }}</a></p>#}
{#            <p><strong>Task Type:</strong> {{ task.task_type.name }}</p>#}
{#            <p class="text-muted"><strong>ID:</strong> {{ task.id }}</p>#}
{#          {% endfor %}#}
{#          <nav aria-label="Completed Tasks Pagination">#}
{#            <ul class="pagination">#}
{#              {% if completed_tasks.has_previous %}#}
{#                <li class="page-item"><a class="page-link" href="?completed_tasks_page={{ completed_tasks.previous_page_number }}">previous</a></li>#}
{#              {% endif %}#}
{#              {% for page in completed_tasks.paginator.page_range %}#}
{#                {% if uncompleted_tasks.number == page %}#}
{#                  <li class="page-item active"><a class="page-link" style="background-color: lightslategrey; color: beige" href="?completed_tasks_page={{ page }}">{{ page }} of {{ completed_tasks.paginator.num_pages  }}</a></li>#}
{#                {% endif %}#}
{#              {% endfor %}#}
{#              {% if completed_tasks.has_next %}#}
{#                <li class="page-item"><a class="page-link" href="?completed_tasks_page={{ completed_tasks.next_page_number }}">next</a></li>#}
{#              {% endif %}#}
{#            </ul>#}
{#          </nav>#}
{#        {% else %}#}
{#          <p>No completed tasks!</p>#}
{#        {% endif %}#}
{##}
{#        <h4>Uncompleted tasks ❌</h4>#}
{#        {% if uncompleted_tasks %}#}
{#          {% for task in uncompleted_tasks %}#}
{#            <hr>#}
{#            <p><strong>Name:</strong> <a href="{{ task.get_absolute_url }}">{{ task.name }}</a></p>#}
{#            <p><strong>Task Type:</strong> {{ task.task_type.name }}</p>#}
{#            <p class="text-muted"><strong>ID:</strong> {{ task.id }}</p>#}
{#          {% endfor %}#}
{#          <nav aria-label="Uncompleted Tasks Pagination">#}
{#            <ul class="pagination">#}
{#              {% if uncompleted_tasks.has_previous %}#}
{#                <li class="page-item"><a class="page-link" href="?uncompleted_tasks_page={{ uncompleted_tasks.previous_page_number }}">previous</a></li>#}
{#              {% endif %}#}
{#              {%for page in uncompleted_tasks.paginator.page_range %}#}
{#                {% if uncompleted_tasks.number == page %}#}
{#                  <li class="page-item active"><a class="page-link" style="background-color: lightslategrey; color: beige" href="?uncompleted_tasks_page={{ page }}">{{ page }} of {{ uncompleted_tasks.paginator.num_pages  }}</a></li>#}
{#                {% endif %}#}
{#              {% endfor %}#}
{#              {% if uncompleted_tasks.has_next %}#}
{#                <li class="page-item"><a class="page-link" href="?uncompleted_tasks_page={{ uncompleted_tasks.next_page_number }}">next</a></li>#}
{#              {% endif %}#}
{#            </ul>#}
{#          </nav>#}
{#        {% else %}#}
{#          <p>No uncompleted tasks!</p>#}
{#        {% endif %}#}
{#      </div>#}
{#    </div>#}
{#  </div>#}
{#{% endblock %}#}

{% extends "base.html" %}

{% block content %}
  <br>
  <div class="container">
    <div class="card">
      <div class="card-header">
        <h1 class="text-center">
          Username: {{ worker.username }}
          <a href="{% url 'manager:worker-delete' pk=worker.id %}" class="btn btn-danger link-to-page">Delete</a>
          <a href="{% url 'manager:worker-update' pk=worker.id %}" class="btn btn-secondary link-to-page">Update worker info</a>
        </h1>
      </div>
      <div class="card-body">
        <hr>
        <div class="row">
          <div class="col-md-6">
            <h3>Personal Information</h3>
            <table class="table table-striped">
              <tr>
                <td><strong>First name:</strong></td>
                <td>{{ worker.first_name }}</td>
              </tr>
              <tr>
                <td><strong>Last name:</strong></td>
                <td>{{ worker.last_name }}</td>
              </tr>
              <tr>
                <td><strong>Position:</strong></td>
                <td>{{ worker.position }}</td>
              </tr>
            </table>
          </div>
          <div class="col-md-6">
            <h3>Tasks</h3>
            <div class="task-section">
              <h4>Completed tasks ✔️</h4>
              {% if completed_tasks %}
                {% for task in completed_tasks %}
                  <hr>
                  <p><strong>Name:</strong> <a href="{{ task.get_absolute_url }}">{{ task.name }}</a></p>
                  <p><strong>Task Type:</strong> {{ task.task_type.name }}</p>
                  <p class="text-muted"><strong>ID:</strong> {{ task.id }}</p>
                {% endfor %}
                <nav aria-label="Completed Tasks Pagination">
                  <ul class="pagination">
                    {% if completed_tasks.has_previous %}
                      <li class="page-item"><a class="page-link" href="?completed_tasks_page={{ completed_tasks.previous_page_number }}">previous</a></li>
                    {% endif %}
                    {% for page in completed_tasks.paginator.page_range %}
                      {% if completed_tasks.number == page %}
                        <li class="page-item active"><a class="page-link" style="background-color: lightslategrey; color: beige" href="?completed_tasks_page={{ page }}">{{ page }} of {{ completed_tasks.paginator.num_pages }}</a></li>
                      {% endif %}
                    {% endfor %}
                    {% if completed_tasks.has_next %}
                      <li class="page-item"><a class="page-link" href="?completed_tasks_page={{ completed_tasks.next_page_number }}">next</a></li>
                    {% endif %}
                  </ul>
                </nav>
              {% else %}
                <p>No completed tasks!</p>
              {% endif %}
            </div>
            <div class="task-section">
              <h4>Uncompleted tasks ❌</h4>
              {% if uncompleted_tasks %}
                {% for task in uncompleted_tasks %}
                  <hr>
                  <p><strong>Name:</strong> <a href="{{ task.get_absolute_url }}">{{ task.name }}</a></p>
                  <p><strong>Task Type:</strong> {{ task.task_type.name }}</p>
                  <p class="text-muted"><strong>ID:</strong> {{ task.id }}</p>
                {% endfor %}
                <nav aria-label="Uncompleted Tasks Pagination">
                  <ul class="pagination">
                    {% if uncompleted_tasks.has_previous %}
                      <li class="page-item"><a class="page-link" href="?uncompleted_tasks_page={{ uncompleted_tasks.previous_page_number }}">previous</a></li>
                    {% endif %}
                    {% for page in uncompleted_tasks.paginator.page_range %}
                      {% if uncompleted_tasks.number == page %}
                        <li class="page-item active"><a class="page-link" style="background-color: lightslategrey; color: beige" href="?uncompleted_tasks_page={{ page }}">{{ page }} of {{ uncompleted_tasks.paginator.num_pages }}</a></li>
                      {% endif %}
                    {% endfor %}
                    {% if uncompleted_tasks.has_next %}
                      <li class="page-item"><a class="page-link" href="?uncompleted_tasks_page={{ uncompleted_tasks.next_page_number }}">next</a></li>
                    {% endif %}
                  </ul>
                </nav>
              {% else %}
                <p>No uncompleted tasks!</p>
              {% endif %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}