manager/urls.py
from django.urls import path

from .views import (
    index,
    WorkerListView,
    TaskListView,
    TaskTypeListView,
    PositionListView,
    WorkerCreateView,
    WorkerDetailView,
    WorkerDeleteView,
    WorkerUpdateView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    TaskDetailView,
    PositionCreateView,
    PositionDetailView,
    PositionDeleteView,
    TaskTypeCreateView,
    TaskTypeDetailView,
    TaskTypeDeleteView,
    CompleteTaskView,
    RejectTaskView,
    PositionUpdateView,

)

urlpatterns = [
    path("", index, name="index"),
    path(
        "task-types/",
        TaskTypeListView.as_view(),
        name="task-type-list",
    ),
    path("tasks/", TaskListView.as_view(), name="task-list"),
    path("tasks/<int:pk>/", TaskDetailView.as_view(), name="task-detail"),
    path("tasks/create/", TaskCreateView.as_view(), name="task-create"),
    path("tasks/<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"),
    path("tasks/<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),
    path("workers/", WorkerListView.as_view(), name="worker-list"),
    path(
        "workers/<int:pk>/", WorkerDetailView.as_view(), name="worker-detail"
    ),
    path("workers/create/", WorkerCreateView.as_view(), name="worker-create"),
    path(
        "workers/<int:pk>/update/",
        WorkerUpdateView.as_view(),
        name="worker-update",
    ),
    path(
        "workers/<int:pk>/delete/",
        WorkerDeleteView.as_view(),
        name="worker-delete",
    ),
    path(
        "positions/",
        PositionListView.as_view(),
        name="position-list",
    ),
    path(
        "posiitions/create/",
        PositionCreateView.as_view(),
        name="position-create",
    ),
    path("positions/<int:pk>/", PositionDetailView.as_view(), name="position-detail"),
    path("positions/<int:pk>/update/", PositionUpdateView.as_view(), name="position-update"),
    path("positions/<int:pk>/delete/", PositionDeleteView.as_view(), name="position-delete"),
    path(
        "task-types/create/",
        TaskTypeCreateView.as_view(),
        name="task-type-create",
    ),
    path(
        "task-types/<int:pk>/",
        TaskTypeDetailView.as_view(),
        name="task-type-detail",
    ),
    path(
        "task-types/<int:pk>/delete/",
        TaskTypeDeleteView.as_view(),
        name="task-type-delete",
    ),
    path('task/<int:pk>/complete/', CompleteTaskView.as_view(), name='task-complete'),
    path('task/<int:pk>/reject/', RejectTaskView.as_view(), name='task-reject'),

]

app_name = "manager"

task_manager/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from manager import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("manager.urls", namespace="manager")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("register", views.register_request, name="register"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/includes/pagination.html
<br>

<div class="d-flex justify-content-center">
  {% load query_transform %}
  {% if is_paginated %}
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a href="?{% query_transform request page=page_obj.previous_page_number %}" class="page-link">prev</a>
        </li>
      {% endif %}
      <li class="page-item active">
        <span class="page-link"
              style="background-color: lightslategrey; color: beige">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
      </li>
      {% if page_obj.has_next %}
        <li class="page-item">
          <a href="?{% query_transform request page=page_obj.next_page_number %}" class="page-link">next</a>
        </li>
      {% endif %}
    </ul>
  {% endif %}
</div>

templates/includes/sidebar.html
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
  <a class="navbar-brand" href="https://github.com/alexlega/Task-manager-project">Task manager project link</a>
  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'manager:index' %}">Home</a>
      </li>
      <li class="nav-item active">

        <a class="nav-link" href="{% url 'manager:worker-list' %}">Workers</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'manager:position-list' %}">Positions</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'manager:task-list' %}">Tasks</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'manager:task-type-list' %}">Task types</a>
      </li>
    </ul>
    <ul class="navbar-nav">
      {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link active" href="{{ user.get_absolute_url }}">{{ user.get_username }}</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'logout' %}?next={{ request.path }}">Logout</a>
        </li>
      {% else %}
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'register' %}?next={{ request.path }}">Sign In</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'login' %}?next={{ request.path }}">Login</a>
        </li>
      {% endif %}
    </ul>
  </div>
</nav>